//go:build ignore
// +build ignore

package main

import (
	"log"
	"os"
	"runtime"
)

func main() {
	// Determine the CFLAGS and LDFLAGS based on the OS
	var cflags, ldflags string
	switch runtime.GOOS {
	case "darwin":
		cflags = "-I/opt/homebrew/include"
		ldflags = "-L/opt/homebrew/lib -lmeos -Wl,-rpath,/opt/homebrew/lib"
	case "linux":
		cflags = "-I/usr/local/include/"
		ldflags = "-L/usr/local/lib -lmeos -Wl,-rpath,/usr/local/lib"
	default:
		log.Fatalf("Unsupported OS: %s", runtime.GOOS)
	}

	// Write the cgo_config.go file with the necessary flags
	configContent := `
// Code generated by generate.go; DO NOT EDIT.

package gomeos

/*
#cgo CFLAGS: ` + cflags + `
#cgo LDFLAGS: ` + ldflags + `
#include "meos.h"
#include "meos_catalog.h"
#include <stdio.h>
#include <stdlib.h>
#include "cast.h"
*/
import "C"
type Interpolation C.int

const (
	INTERP_NONE    Interpolation = C.INTERP_NONE
	DISCRETE       Interpolation = C.DISCRETE
	STEP           Interpolation = C.STEP
	LINEAR                       = C.LINEAR
	ANYTEMPSUBTYPE               = C.ANYTEMPSUBTYPE /**< Any temporal subtype */
	TINSTANT                     = C.TINSTANT       /**< Temporal instant subtype */
	TSEQUENCE                    = C.TSEQUENCE      /**< Temporal sequence subtype */
	TSEQUENCESET                 = C.TSEQUENCESET   /**< Temporal sequence set subtype */
	T_TBOOL                      = C.T_TBOOL        /**< temporal boolean type */
	T_TFLOAT                     = C.T_TFLOAT       /**< temporal float type */
	T_TINT                       = C.T_TINT         /**< temporal integer type */
	T_TTEXT                      = C.T_TTEXT        /**< temporal text type */
	T_TGEOMPOINT                 = C.T_TGEOMPOINT   /**< temporal geometry point type */
	T_TGEOGPOINT                 = C.T_TGEOGPOINT   /**< temporal geography point type */
)
`
	if err := os.WriteFile("cgo_flag_config.go", []byte(configContent), 0644); err != nil {
		log.Fatalf("Failed to write cgo_flag_config.go: %v", err)
	}
}
