package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type DateSpanSet struct {
	SpanSet
}

// DateSpanSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func DateSpanSetFromPointer(p unsafe.Pointer) *DateSpanSet {
	if p == nil {
		return nil
	}
	v := &DateSpanSet{}
	v.ptr = p
	return v
}

// DateSpanSetIn is MEOS datespanset_in.
func DateSpanSetIn(str string) (*SpanSet, error) {
	_r0, _err := functions.DatespansetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Out is MEOS datespanset_out.
func (x *DateSpanSet) Out() (string, error) {
	_r0, _err := functions.DatespansetOut(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// ToTstzspanset is MEOS datespanset_to_tstzspanset.
func (x *DateSpanSet) ToTstzspanset() (*SpanSet, error) {
	_r0, _err := functions.DatespansetToTstzspanset(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// DateN is MEOS datespanset_date_n.
func (x *DateSpanSet) DateN(n int) (int32, bool, error) {
	_found, _value, _err := functions.DatespansetDateN(functions.SpanSetFromPointer(x.Pointer()), n)
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Dates is MEOS datespanset_dates.
func (x *DateSpanSet) Dates() (*Set, error) {
	_r0, _err := functions.DatespansetDates(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Duration is MEOS datespanset_duration.
func (x *DateSpanSet) Duration(boundspan bool) (*functions.Interval, error) {
	_r0, _err := functions.DatespansetDuration(functions.SpanSetFromPointer(x.Pointer()), boundspan)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// EndDate is MEOS datespanset_end_date.
func (x *DateSpanSet) EndDate() (int32, error) {
	_r0, _err := functions.DatespansetEndDate(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Lower is MEOS datespanset_lower.
func (x *DateSpanSet) Lower() (int32, error) {
	_r0, _err := functions.DatespansetLower(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// NumDates is MEOS datespanset_num_dates.
func (x *DateSpanSet) NumDates() (int, error) {
	_r0, _err := functions.DatespansetNumDates(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// StartDate is MEOS datespanset_start_date.
func (x *DateSpanSet) StartDate() (int32, error) {
	_r0, _err := functions.DatespansetStartDate(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Upper is MEOS datespanset_upper.
func (x *DateSpanSet) Upper() (int32, error) {
	_r0, _err := functions.DatespansetUpper(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ShiftScale is MEOS datespanset_shift_scale.
func (x *DateSpanSet) ShiftScale(shift int, width int, hasshift bool, haswidth bool) (*SpanSet, error) {
	_r0, _err := functions.DatespansetShiftScale(functions.SpanSetFromPointer(x.Pointer()), shift, width, hasshift, haswidth)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Bins is MEOS datespanset_bins.
func (x *DateSpanSet) Bins(duration *functions.Interval, torigin int32, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.DatespansetBins(functions.SpanSetFromPointer(x.Pointer()), duration, torigin, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}
