package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type RTree struct {
	Value
}

// RTreeFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func RTreeFromPointer(p unsafe.Pointer) *RTree {
	if p == nil {
		return nil
	}
	v := &RTree{}
	v.ptr = p
	return v
}

// RTreeCreateIntspan is MEOS rtree_create_intspan.
func RTreeCreateIntspan() (*RTree, error) {
	_r0, _err := functions.RtreeCreateIntspan()
	if _err != nil {
		return nil, _err
	}
	return RTreeFromPointer(_r0.Pointer()), nil
}

// RTreeCreateBigintspan is MEOS rtree_create_bigintspan.
func RTreeCreateBigintspan() (*RTree, error) {
	_r0, _err := functions.RtreeCreateBigintspan()
	if _err != nil {
		return nil, _err
	}
	return RTreeFromPointer(_r0.Pointer()), nil
}

// RTreeCreateFloatspan is MEOS rtree_create_floatspan.
func RTreeCreateFloatspan() (*RTree, error) {
	_r0, _err := functions.RtreeCreateFloatspan()
	if _err != nil {
		return nil, _err
	}
	return RTreeFromPointer(_r0.Pointer()), nil
}

// RTreeCreateDatespan is MEOS rtree_create_datespan.
func RTreeCreateDatespan() (*RTree, error) {
	_r0, _err := functions.RtreeCreateDatespan()
	if _err != nil {
		return nil, _err
	}
	return RTreeFromPointer(_r0.Pointer()), nil
}

// RTreeCreateTstzspan is MEOS rtree_create_tstzspan.
func RTreeCreateTstzspan() (*RTree, error) {
	_r0, _err := functions.RtreeCreateTstzspan()
	if _err != nil {
		return nil, _err
	}
	return RTreeFromPointer(_r0.Pointer()), nil
}

// RTreeCreateTbox is MEOS rtree_create_tbox.
func RTreeCreateTbox() (*RTree, error) {
	_r0, _err := functions.RtreeCreateTBOX()
	if _err != nil {
		return nil, _err
	}
	return RTreeFromPointer(_r0.Pointer()), nil
}

// RTreeCreateStbox is MEOS rtree_create_stbox.
func RTreeCreateStbox() (*RTree, error) {
	_r0, _err := functions.RtreeCreateSTBOX()
	if _err != nil {
		return nil, _err
	}
	return RTreeFromPointer(_r0.Pointer()), nil
}

// RTreeCreateTpcbox is MEOS rtree_create_tpcbox.
func RTreeCreateTpcbox() (*RTree, error) {
	_r0, _err := functions.RtreeCreateTpcbox()
	if _err != nil {
		return nil, _err
	}
	return RTreeFromPointer(_r0.Pointer()), nil
}

// Free is MEOS rtree_free.
func (x *RTree) Free() error {
	return functions.RtreeFree(functions.RTreeFromPointer(x.Pointer()))
}

// NumEntries is MEOS rtree_num_entries.
func (x *RTree) NumEntries() (int, error) {
	_r0, _err := functions.RtreeNumEntries(functions.RTreeFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// MemSize is MEOS rtree_mem_size.
func (x *RTree) MemSize() (int64, error) {
	_r0, _err := functions.RtreeMemSize(functions.RTreeFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Height is MEOS rtree_height.
func (x *RTree) Height() (int, error) {
	_r0, _err := functions.RtreeHeight(functions.RTreeFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Insert is MEOS rtree_insert.
func (x *RTree) Insert(box unsafe.Pointer, id int64) (bool, error) {
	_r0, _err := functions.RtreeInsert(functions.RTreeFromPointer(x.Pointer()), box, id)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Load is MEOS rtree_load.
func (x *RTree) Load(boxes unsafe.Pointer, ids unsafe.Pointer, count int) (bool, error) {
	_r0, _err := functions.RtreeLoad(functions.RTreeFromPointer(x.Pointer()), boxes, ids, count)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// InsertTemporal is MEOS rtree_insert_temporal.
func (x *RTree) InsertTemporal(temp *Temporal, id int64) (bool, error) {
	_r0, _err := functions.RtreeInsertTemporal(functions.RTreeFromPointer(x.Pointer()), functions.TemporalFromPointer(temp.Pointer()), id)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// InsertTemporalSplit is MEOS rtree_insert_temporal_split.
func (x *RTree) InsertTemporalSplit(temp *Temporal, id int64, maxboxes int) (bool, error) {
	_r0, _err := functions.RtreeInsertTemporalSplit(functions.RTreeFromPointer(x.Pointer()), functions.TemporalFromPointer(temp.Pointer()), id, maxboxes)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Search is MEOS rtree_search.
func (x *RTree) Search(op functions.IndexSearchOp, query unsafe.Pointer) (int, *MeosArray, error) {
	_r0, _r1, _err := functions.RtreeSearch(functions.RTreeFromPointer(x.Pointer()), op, query)
	if _err != nil {
		return 0, nil, _err
	}
	return _r0, MeosArrayFromPointer(_r1.Pointer()), nil
}

// Join is MEOS rtree_join.
func (x *RTree) Join(rtree2 *RTree, op functions.IndexSearchOp) (int, *MeosArray, error) {
	_r0, _r1, _err := functions.RtreeJoin(functions.RTreeFromPointer(x.Pointer()), functions.RTreeFromPointer(rtree2.Pointer()), op)
	if _err != nil {
		return 0, nil, _err
	}
	return _r0, MeosArrayFromPointer(_r1.Pointer()), nil
}

// SearchTemporal is MEOS rtree_search_temporal.
func (x *RTree) SearchTemporal(op functions.IndexSearchOp, temp *Temporal) (int, *MeosArray, error) {
	_r0, _r1, _err := functions.RtreeSearchTemporal(functions.RTreeFromPointer(x.Pointer()), op, functions.TemporalFromPointer(temp.Pointer()))
	if _err != nil {
		return 0, nil, _err
	}
	return _r0, MeosArrayFromPointer(_r1.Pointer()), nil
}
