package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type STBox struct {
	Box
}

// STBoxFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func STBoxFromPointer(p unsafe.Pointer) *STBox {
	if p == nil {
		return nil
	}
	v := &STBox{}
	v.ptr = p
	return v
}

// AsHEXWKB is MEOS stbox_as_hexwkb.
func (x *STBox) AsHEXWKB(variant uint8, size_out unsafe.Pointer) (string, error) {
	_r0, _err := functions.STBOXAsHexwkb(functions.STBoxFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsWKB is MEOS stbox_as_wkb.
func (x *STBox) AsWKB(variant uint8, size_out unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.STBOXAsWKB(functions.STBoxFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// STBoxFromHEXWKB is MEOS stbox_from_hexwkb.
func STBoxFromHEXWKB(hexwkb string) (*STBox, error) {
	_r0, _err := functions.STBOXFromHexwkb(hexwkb)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// STBoxFromWKB is MEOS stbox_from_wkb.
func STBoxFromWKB(wkb unsafe.Pointer, size uint) (*STBox, error) {
	_r0, _err := functions.STBOXFromWKB(wkb, size)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// STBoxIn is MEOS stbox_in.
func STBoxIn(str string) (*STBox, error) {
	_r0, _err := functions.STBOXIn(str)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// Out is MEOS stbox_out.
func (x *STBox) Out(maxdd int) (string, error) {
	_r0, _err := functions.STBOXOut(functions.STBoxFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// Copy is MEOS stbox_copy.
func (x *STBox) Copy() (*STBox, error) {
	_r0, _err := functions.STBOXCopy(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// STBoxMake is MEOS stbox_make.
func STBoxMake(hasx bool, hasz bool, geodetic bool, srid int32, xmin float64, xmax float64, ymin float64, ymax float64, zmin float64, zmax float64, s *Span) (*STBox, error) {
	_r0, _err := functions.STBOXMake(hasx, hasz, geodetic, srid, xmin, xmax, ymin, ymax, zmin, zmax, functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// ToBox3d is MEOS stbox_to_box3d.
func (x *STBox) ToBox3d() (*functions.Box3D, error) {
	_r0, _err := functions.STBOXToBox3d(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// ToGbox is MEOS stbox_to_gbox.
func (x *STBox) ToGbox() (*functions.GBox, error) {
	_r0, _err := functions.STBOXToGbox(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// ToGeo is MEOS stbox_to_geo.
func (x *STBox) ToGeo() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.STBOXToGeo(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// ToTstzspan is MEOS stbox_to_tstzspan.
func (x *STBox) ToTstzspan() (*Span, error) {
	_r0, _err := functions.STBOXToTstzspan(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Area is MEOS stbox_area.
func (x *STBox) Area(spheroid bool) (float64, error) {
	_r0, _err := functions.STBOXArea(functions.STBoxFromPointer(x.Pointer()), spheroid)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Hash is MEOS stbox_hash.
func (x *STBox) Hash() (uint32, error) {
	_r0, _err := functions.STBOXHash(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// HashExtended is MEOS stbox_hash_extended.
func (x *STBox) HashExtended(seed uint64) (uint64, error) {
	_r0, _err := functions.STBOXHashExtended(functions.STBoxFromPointer(x.Pointer()), seed)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Hast is MEOS stbox_hast.
func (x *STBox) Hast() (bool, error) {
	_r0, _err := functions.STBOXHast(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Hasx is MEOS stbox_hasx.
func (x *STBox) Hasx() (bool, error) {
	_r0, _err := functions.STBOXHasx(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Hasz is MEOS stbox_hasz.
func (x *STBox) Hasz() (bool, error) {
	_r0, _err := functions.STBOXHasz(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Isgeodetic is MEOS stbox_isgeodetic.
func (x *STBox) Isgeodetic() (bool, error) {
	_r0, _err := functions.STBOXIsgeodetic(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Perimeter is MEOS stbox_perimeter.
func (x *STBox) Perimeter(spheroid bool) (float64, error) {
	_r0, _err := functions.STBOXPerimeter(functions.STBoxFromPointer(x.Pointer()), spheroid)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Tmax is MEOS stbox_tmax.
func (x *STBox) Tmax() (int64, bool, error) {
	_found, _value, _err := functions.STBOXTmax(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// TmaxInc is MEOS stbox_tmax_inc.
func (x *STBox) TmaxInc() (bool, bool, error) {
	_found, _value, _err := functions.STBOXTmaxInc(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, false, _err
	}
	if !_found {
		return false, false, nil
	}
	return _value, true, nil
}

// Tmin is MEOS stbox_tmin.
func (x *STBox) Tmin() (int64, bool, error) {
	_found, _value, _err := functions.STBOXTmin(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// TminInc is MEOS stbox_tmin_inc.
func (x *STBox) TminInc() (bool, bool, error) {
	_found, _value, _err := functions.STBOXTminInc(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, false, _err
	}
	if !_found {
		return false, false, nil
	}
	return _value, true, nil
}

// Volume is MEOS stbox_volume.
func (x *STBox) Volume() (float64, error) {
	_r0, _err := functions.STBOXVolume(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Xmax is MEOS stbox_xmax.
func (x *STBox) Xmax() (float64, bool, error) {
	_found, _value, _err := functions.STBOXXmax(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Xmin is MEOS stbox_xmin.
func (x *STBox) Xmin() (float64, bool, error) {
	_found, _value, _err := functions.STBOXXmin(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Ymax is MEOS stbox_ymax.
func (x *STBox) Ymax() (float64, bool, error) {
	_found, _value, _err := functions.STBOXYmax(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Ymin is MEOS stbox_ymin.
func (x *STBox) Ymin() (float64, bool, error) {
	_found, _value, _err := functions.STBOXYmin(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Zmax is MEOS stbox_zmax.
func (x *STBox) Zmax() (float64, bool, error) {
	_found, _value, _err := functions.STBOXZmax(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Zmin is MEOS stbox_zmin.
func (x *STBox) Zmin() (float64, bool, error) {
	_found, _value, _err := functions.STBOXZmin(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// ExpandSpace is MEOS stbox_expand_space.
func (x *STBox) ExpandSpace(d float64) (*STBox, error) {
	_r0, _err := functions.STBOXExpandSpace(functions.STBoxFromPointer(x.Pointer()), d)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// ExpandTime is MEOS stbox_expand_time.
func (x *STBox) ExpandTime(interv *functions.Interval) (*STBox, error) {
	_r0, _err := functions.STBOXExpandTime(functions.STBoxFromPointer(x.Pointer()), interv)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// GetSpace is MEOS stbox_get_space.
func (x *STBox) GetSpace() (*STBox, error) {
	_r0, _err := functions.STBOXGetSpace(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// QuadSplit is MEOS stbox_quad_split.
func (x *STBox) QuadSplit(count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.STBOXQuadSplit(functions.STBoxFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// Round is MEOS stbox_round.
func (x *STBox) Round(maxdd int) (*STBox, error) {
	_r0, _err := functions.STBOXRound(functions.STBoxFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// ShiftScaleTime is MEOS stbox_shift_scale_time.
func (x *STBox) ShiftScaleTime(shift *functions.Interval, duration *functions.Interval) (*STBox, error) {
	_r0, _err := functions.STBOXShiftScaleTime(functions.STBoxFromPointer(x.Pointer()), shift, duration)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// SetSRID is MEOS stbox_set_srid.
func (x *STBox) SetSRID(srid int32) (*STBox, error) {
	_r0, _err := functions.STBOXSetSRID(functions.STBoxFromPointer(x.Pointer()), srid)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// SRID is MEOS stbox_srid.
func (x *STBox) SRID() (int32, error) {
	_r0, _err := functions.STBOXSRID(functions.STBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Transform is MEOS stbox_transform.
func (x *STBox) Transform(srid int32) (*STBox, error) {
	_r0, _err := functions.STBOXTransform(functions.STBoxFromPointer(x.Pointer()), srid)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// TransformPipeline is MEOS stbox_transform_pipeline.
func (x *STBox) TransformPipeline(pipelinestr string, srid int32, is_forward bool) (*STBox, error) {
	_r0, _err := functions.STBOXTransformPipeline(functions.STBoxFromPointer(x.Pointer()), pipelinestr, srid, is_forward)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// Cmp is MEOS stbox_cmp.
func (x *STBox) Cmp(box2 *STBox) (int, error) {
	_r0, _err := functions.STBOXCmp(functions.STBoxFromPointer(x.Pointer()), functions.STBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Eq is MEOS stbox_eq.
func (x *STBox) Eq(box2 *STBox) (bool, error) {
	_r0, _err := functions.STBOXEq(functions.STBoxFromPointer(x.Pointer()), functions.STBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ge is MEOS stbox_ge.
func (x *STBox) Ge(box2 *STBox) (bool, error) {
	_r0, _err := functions.STBOXGe(functions.STBoxFromPointer(x.Pointer()), functions.STBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Gt is MEOS stbox_gt.
func (x *STBox) Gt(box2 *STBox) (bool, error) {
	_r0, _err := functions.STBOXGt(functions.STBoxFromPointer(x.Pointer()), functions.STBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Le is MEOS stbox_le.
func (x *STBox) Le(box2 *STBox) (bool, error) {
	_r0, _err := functions.STBOXLe(functions.STBoxFromPointer(x.Pointer()), functions.STBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Lt is MEOS stbox_lt.
func (x *STBox) Lt(box2 *STBox) (bool, error) {
	_r0, _err := functions.STBOXLt(functions.STBoxFromPointer(x.Pointer()), functions.STBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ne is MEOS stbox_ne.
func (x *STBox) Ne(box2 *STBox) (bool, error) {
	_r0, _err := functions.STBOXNe(functions.STBoxFromPointer(x.Pointer()), functions.STBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// SpatialDistance is MEOS stbox_spatial_distance.
func (x *STBox) SpatialDistance(box2 *STBox) (float64, error) {
	_r0, _err := functions.STBOXSpatialDistance(functions.STBoxFromPointer(x.Pointer()), functions.STBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// STBoxGetSpaceTile is MEOS stbox_get_space_tile.
func STBoxGetSpaceTile(point *TRGeometrySeqSet, xsize float64, ysize float64, zsize float64, sorigin *TRGeometrySeqSet) (*STBox, error) {
	_r0, _err := functions.STBOXGetSpaceTile(functions.GeomFromPointer(point.Pointer()), xsize, ysize, zsize, functions.GeomFromPointer(sorigin.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// STBoxGetSpaceTimeTile is MEOS stbox_get_space_time_tile.
func STBoxGetSpaceTimeTile(point *TRGeometrySeqSet, t int64, xsize float64, ysize float64, zsize float64, duration *functions.Interval, sorigin *TRGeometrySeqSet, torigin int64) (*STBox, error) {
	_r0, _err := functions.STBOXGetSpaceTimeTile(functions.GeomFromPointer(point.Pointer()), t, xsize, ysize, zsize, duration, functions.GeomFromPointer(sorigin.Pointer()), torigin)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// STBoxGetTimeTile is MEOS stbox_get_time_tile.
func STBoxGetTimeTile(t int64, duration *functions.Interval, torigin int64) (*STBox, error) {
	_r0, _err := functions.STBOXGetTimeTile(t, duration, torigin)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// SpaceTiles is MEOS stbox_space_tiles.
func (x *STBox) SpaceTiles(xsize float64, ysize float64, zsize float64, sorigin *TRGeometrySeqSet, border_inc bool, count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.STBOXSpaceTiles(functions.STBoxFromPointer(x.Pointer()), xsize, ysize, zsize, functions.GeomFromPointer(sorigin.Pointer()), border_inc, count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// SpaceTimeTiles is MEOS stbox_space_time_tiles.
func (x *STBox) SpaceTimeTiles(xsize float64, ysize float64, zsize float64, duration *functions.Interval, sorigin *TRGeometrySeqSet, torigin int64, border_inc bool, count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.STBOXSpaceTimeTiles(functions.STBoxFromPointer(x.Pointer()), xsize, ysize, zsize, duration, functions.GeomFromPointer(sorigin.Pointer()), torigin, border_inc, count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// TimeTiles is MEOS stbox_time_tiles.
func (x *STBox) TimeTiles(duration *functions.Interval, torigin int64, border_inc bool, count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.STBOXTimeTiles(functions.STBoxFromPointer(x.Pointer()), duration, torigin, border_inc, count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}
