package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TBox struct {
	Box
}

// TBoxFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TBoxFromPointer(p unsafe.Pointer) *TBox {
	if p == nil {
		return nil
	}
	v := &TBox{}
	v.ptr = p
	return v
}

// AsHEXWKB is MEOS tbox_as_hexwkb.
func (x *TBox) AsHEXWKB(variant uint8, size_out unsafe.Pointer) (string, error) {
	_r0, _err := functions.TBOXAsHexwkb(functions.TBoxFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsWKB is MEOS tbox_as_wkb.
func (x *TBox) AsWKB(variant uint8, size_out unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TBOXAsWKB(functions.TBoxFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// TBoxFromHEXWKB is MEOS tbox_from_hexwkb.
func TBoxFromHEXWKB(hexwkb string) (*TBox, error) {
	_r0, _err := functions.TBOXFromHexwkb(hexwkb)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// TBoxFromWKB is MEOS tbox_from_wkb.
func TBoxFromWKB(wkb unsafe.Pointer, size uint) (*TBox, error) {
	_r0, _err := functions.TBOXFromWKB(wkb, size)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// TBoxIn is MEOS tbox_in.
func TBoxIn(str string) (*TBox, error) {
	_r0, _err := functions.TBOXIn(str)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// Out is MEOS tbox_out.
func (x *TBox) Out(maxdd int) (string, error) {
	_r0, _err := functions.TBOXOut(functions.TBoxFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// Copy is MEOS tbox_copy.
func (x *TBox) Copy() (*TBox, error) {
	_r0, _err := functions.TBOXCopy(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// TBoxMake is MEOS tbox_make.
func TBoxMake(s *Span, p *Span) (*TBox, error) {
	_r0, _err := functions.TBOXMake(functions.SpanFromPointer(s.Pointer()), functions.SpanFromPointer(p.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// ToIntspan is MEOS tbox_to_intspan.
func (x *TBox) ToIntspan() (*Span, error) {
	_r0, _err := functions.TBOXToIntspan(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToBigintspan is MEOS tbox_to_bigintspan.
func (x *TBox) ToBigintspan() (*Span, error) {
	_r0, _err := functions.TBOXToBigintspan(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToFloatspan is MEOS tbox_to_floatspan.
func (x *TBox) ToFloatspan() (*Span, error) {
	_r0, _err := functions.TBOXToFloatspan(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToTstzspan is MEOS tbox_to_tstzspan.
func (x *TBox) ToTstzspan() (*Span, error) {
	_r0, _err := functions.TBOXToTstzspan(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Hash is MEOS tbox_hash.
func (x *TBox) Hash() (uint32, error) {
	_r0, _err := functions.TBOXHash(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// HashExtended is MEOS tbox_hash_extended.
func (x *TBox) HashExtended(seed uint64) (uint64, error) {
	_r0, _err := functions.TBOXHashExtended(functions.TBoxFromPointer(x.Pointer()), seed)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Hast is MEOS tbox_hast.
func (x *TBox) Hast() (bool, error) {
	_r0, _err := functions.TBOXHast(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Hasx is MEOS tbox_hasx.
func (x *TBox) Hasx() (bool, error) {
	_r0, _err := functions.TBOXHasx(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Tmax is MEOS tbox_tmax.
func (x *TBox) Tmax() (int64, bool, error) {
	_found, _value, _err := functions.TBOXTmax(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// TmaxInc is MEOS tbox_tmax_inc.
func (x *TBox) TmaxInc() (bool, bool, error) {
	_found, _value, _err := functions.TBOXTmaxInc(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, false, _err
	}
	if !_found {
		return false, false, nil
	}
	return _value, true, nil
}

// Tmin is MEOS tbox_tmin.
func (x *TBox) Tmin() (int64, bool, error) {
	_found, _value, _err := functions.TBOXTmin(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// TminInc is MEOS tbox_tmin_inc.
func (x *TBox) TminInc() (bool, bool, error) {
	_found, _value, _err := functions.TBOXTminInc(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, false, _err
	}
	if !_found {
		return false, false, nil
	}
	return _value, true, nil
}

// Xmax is MEOS tbox_xmax.
func (x *TBox) Xmax() (float64, bool, error) {
	_found, _value, _err := functions.TBOXXmax(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// XmaxInc is MEOS tbox_xmax_inc.
func (x *TBox) XmaxInc() (bool, bool, error) {
	_found, _value, _err := functions.TBOXXmaxInc(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, false, _err
	}
	if !_found {
		return false, false, nil
	}
	return _value, true, nil
}

// Xmin is MEOS tbox_xmin.
func (x *TBox) Xmin() (float64, bool, error) {
	_found, _value, _err := functions.TBOXXmin(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// XminInc is MEOS tbox_xmin_inc.
func (x *TBox) XminInc() (bool, bool, error) {
	_found, _value, _err := functions.TBOXXminInc(functions.TBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, false, _err
	}
	if !_found {
		return false, false, nil
	}
	return _value, true, nil
}

// ExpandTime is MEOS tbox_expand_time.
func (x *TBox) ExpandTime(interv *functions.Interval) (*TBox, error) {
	_r0, _err := functions.TBOXExpandTime(functions.TBoxFromPointer(x.Pointer()), interv)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// Round is MEOS tbox_round.
func (x *TBox) Round(maxdd int) (*TBox, error) {
	_r0, _err := functions.TBOXRound(functions.TBoxFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// ShiftScaleTime is MEOS tbox_shift_scale_time.
func (x *TBox) ShiftScaleTime(shift *functions.Interval, duration *functions.Interval) (*TBox, error) {
	_r0, _err := functions.TBOXShiftScaleTime(functions.TBoxFromPointer(x.Pointer()), shift, duration)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// Cmp is MEOS tbox_cmp.
func (x *TBox) Cmp(box2 *TBox) (int, error) {
	_r0, _err := functions.TBOXCmp(functions.TBoxFromPointer(x.Pointer()), functions.TBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Eq is MEOS tbox_eq.
func (x *TBox) Eq(box2 *TBox) (bool, error) {
	_r0, _err := functions.TBOXEq(functions.TBoxFromPointer(x.Pointer()), functions.TBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ge is MEOS tbox_ge.
func (x *TBox) Ge(box2 *TBox) (bool, error) {
	_r0, _err := functions.TBOXGe(functions.TBoxFromPointer(x.Pointer()), functions.TBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Gt is MEOS tbox_gt.
func (x *TBox) Gt(box2 *TBox) (bool, error) {
	_r0, _err := functions.TBOXGt(functions.TBoxFromPointer(x.Pointer()), functions.TBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Le is MEOS tbox_le.
func (x *TBox) Le(box2 *TBox) (bool, error) {
	_r0, _err := functions.TBOXLe(functions.TBoxFromPointer(x.Pointer()), functions.TBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Lt is MEOS tbox_lt.
func (x *TBox) Lt(box2 *TBox) (bool, error) {
	_r0, _err := functions.TBOXLt(functions.TBoxFromPointer(x.Pointer()), functions.TBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ne is MEOS tbox_ne.
func (x *TBox) Ne(box2 *TBox) (bool, error) {
	_r0, _err := functions.TBOXNe(functions.TBoxFromPointer(x.Pointer()), functions.TBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}
