package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

// Temporal is superclass of every temporal type; temporal_* functions are late-bound over `subtype` and `temptype`.

type Temporal struct {
	handle
}

// TemporalFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TemporalFromPointer(p unsafe.Pointer) *Temporal {
	if p == nil {
		return nil
	}
	v := &Temporal{}
	v.ptr = p
	return v
}

// AsHEXWKB is MEOS temporal_as_hexwkb.
func (x *Temporal) AsHEXWKB(variant uint8, size_out unsafe.Pointer) (string, error) {
	_r0, _err := functions.TemporalAsHexwkb(functions.TemporalFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsMFJSON is MEOS temporal_as_mfjson.
func (x *Temporal) AsMFJSON(with_bbox bool, flags int, precision int, srs string) (string, error) {
	_r0, _err := functions.TemporalAsMFJSON(functions.TemporalFromPointer(x.Pointer()), with_bbox, flags, precision, srs)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsWKB is MEOS temporal_as_wkb.
func (x *Temporal) AsWKB(variant uint8, size_out unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TemporalAsWKB(functions.TemporalFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// TemporalFromHEXWKB is MEOS temporal_from_hexwkb.
func TemporalFromHEXWKB(hexwkb string) (*Temporal, error) {
	_r0, _err := functions.TemporalFromHexwkb(hexwkb)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TemporalFromWKB is MEOS temporal_from_wkb.
func TemporalFromWKB(wkb unsafe.Pointer, size uint) (*Temporal, error) {
	_r0, _err := functions.TemporalFromWKB(wkb, size)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Copy is MEOS temporal_copy.
func (x *Temporal) Copy() (*Temporal, error) {
	_r0, _err := functions.TemporalCopy(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTstzspan is MEOS temporal_to_tstzspan.
func (x *Temporal) ToTstzspan() (*Span, error) {
	_r0, _err := functions.TemporalToTstzspan(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Duration is MEOS temporal_duration.
func (x *Temporal) Duration(boundspan bool) (*functions.Interval, error) {
	_r0, _err := functions.TemporalDuration(functions.TemporalFromPointer(x.Pointer()), boundspan)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// EndInstant is MEOS temporal_end_instant.
func (x *Temporal) EndInstant() (*Temporal, error) {
	_r0, _err := functions.TemporalEndInstant(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// EndSequence is MEOS temporal_end_sequence.
func (x *Temporal) EndSequence() (*Temporal, error) {
	_r0, _err := functions.TemporalEndSequence(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// EndTimestamptz is MEOS temporal_end_timestamptz.
func (x *Temporal) EndTimestamptz() (int64, error) {
	_r0, _err := functions.TemporalEndTimestamptz(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Hash is MEOS temporal_hash.
func (x *Temporal) Hash() (uint32, error) {
	_r0, _err := functions.TemporalHash(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// HashExtended is MEOS temporal_hash_extended.
func (x *Temporal) HashExtended(seed uint64) (uint64, error) {
	_r0, _err := functions.TemporalHashExtended(functions.TemporalFromPointer(x.Pointer()), seed)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// InstantN is MEOS temporal_instant_n.
func (x *Temporal) InstantN(n int) (*Temporal, error) {
	_r0, _err := functions.TemporalInstantN(functions.TemporalFromPointer(x.Pointer()), n)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Instants is MEOS temporal_instants.
func (x *Temporal) Instants(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TemporalInstants(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Interp is MEOS temporal_interp.
func (x *Temporal) Interp() (string, error) {
	_r0, _err := functions.TemporalInterp(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// LowerInc is MEOS temporal_lower_inc.
func (x *Temporal) LowerInc() (bool, error) {
	_r0, _err := functions.TemporalLowerInc(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// MaxInstant is MEOS temporal_max_instant.
func (x *Temporal) MaxInstant() (*Temporal, error) {
	_r0, _err := functions.TemporalMaxInstant(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinInstant is MEOS temporal_min_instant.
func (x *Temporal) MinInstant() (*Temporal, error) {
	_r0, _err := functions.TemporalMinInstant(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// NumInstants is MEOS temporal_num_instants.
func (x *Temporal) NumInstants() (int, error) {
	_r0, _err := functions.TemporalNumInstants(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// NumSequences is MEOS temporal_num_sequences.
func (x *Temporal) NumSequences() (int, error) {
	_r0, _err := functions.TemporalNumSequences(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// NumTimestamps is MEOS temporal_num_timestamps.
func (x *Temporal) NumTimestamps() (int, error) {
	_r0, _err := functions.TemporalNumTimestamps(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// SegmDuration is MEOS temporal_segm_duration.
func (x *Temporal) SegmDuration(duration *functions.Interval, atleast bool, strict bool) (*Temporal, error) {
	_r0, _err := functions.TemporalSegmDuration(functions.TemporalFromPointer(x.Pointer()), duration, atleast, strict)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Segments is MEOS temporal_segments.
func (x *Temporal) Segments(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TemporalSegments(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// SequenceN is MEOS temporal_sequence_n.
func (x *Temporal) SequenceN(i int) (*Temporal, error) {
	_r0, _err := functions.TemporalSequenceN(functions.TemporalFromPointer(x.Pointer()), i)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Sequences is MEOS temporal_sequences.
func (x *Temporal) Sequences(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TemporalSequences(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// StartInstant is MEOS temporal_start_instant.
func (x *Temporal) StartInstant() (*Temporal, error) {
	_r0, _err := functions.TemporalStartInstant(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// StartSequence is MEOS temporal_start_sequence.
func (x *Temporal) StartSequence() (*Temporal, error) {
	_r0, _err := functions.TemporalStartSequence(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// StartTimestamptz is MEOS temporal_start_timestamptz.
func (x *Temporal) StartTimestamptz() (int64, error) {
	_r0, _err := functions.TemporalStartTimestamptz(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Stops is MEOS temporal_stops.
func (x *Temporal) Stops(maxdist float64, minduration *functions.Interval) (*Temporal, error) {
	_r0, _err := functions.TemporalStops(functions.TemporalFromPointer(x.Pointer()), maxdist, minduration)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Subtype is MEOS temporal_subtype.
func (x *Temporal) Subtype() (string, error) {
	_r0, _err := functions.TemporalSubtype(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// BasetypeName is MEOS temporal_basetype_name.
func (x *Temporal) BasetypeName() (string, error) {
	_r0, _err := functions.TemporalBasetypeName(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// Time is MEOS temporal_time.
func (x *Temporal) Time() (*SpanSet, error) {
	_r0, _err := functions.TemporalTime(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Timestamps is MEOS temporal_timestamps.
func (x *Temporal) Timestamps(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TemporalTimestamps(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// TimestamptzN is MEOS temporal_timestamptz_n.
func (x *Temporal) TimestamptzN(n int) (int64, bool, error) {
	_found, _value, _err := functions.TemporalTimestamptzN(functions.TemporalFromPointer(x.Pointer()), n)
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// UpperInc is MEOS temporal_upper_inc.
func (x *Temporal) UpperInc() (bool, error) {
	_r0, _err := functions.TemporalUpperInc(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Round is MEOS temporal_round.
func (x *Temporal) Round(maxdd int) (*Temporal, error) {
	_r0, _err := functions.TemporalRound(functions.TemporalFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ScaleTime is MEOS temporal_scale_time.
func (x *Temporal) ScaleTime(duration *functions.Interval) (*Temporal, error) {
	_r0, _err := functions.TemporalScaleTime(functions.TemporalFromPointer(x.Pointer()), duration)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// SetInterp is MEOS temporal_set_interp.
func (x *Temporal) SetInterp(interp functions.Interpolation) (*Temporal, error) {
	_r0, _err := functions.TemporalSetInterp(functions.TemporalFromPointer(x.Pointer()), interp)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ShiftScaleTime is MEOS temporal_shift_scale_time.
func (x *Temporal) ShiftScaleTime(shift *functions.Interval, duration *functions.Interval) (*Temporal, error) {
	_r0, _err := functions.TemporalShiftScaleTime(functions.TemporalFromPointer(x.Pointer()), shift, duration)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ShiftTime is MEOS temporal_shift_time.
func (x *Temporal) ShiftTime(shift *functions.Interval) (*Temporal, error) {
	_r0, _err := functions.TemporalShiftTime(functions.TemporalFromPointer(x.Pointer()), shift)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AsTinstant is MEOS temporal_as_tinstant.
func (x *Temporal) AsTinstant() (*Temporal, error) {
	_r0, _err := functions.TemporalAsTinstant(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AsTsequence is MEOS temporal_as_tsequence.
func (x *Temporal) AsTsequence(interp functions.Interpolation) (*Temporal, error) {
	_r0, _err := functions.TemporalAsTsequence(functions.TemporalFromPointer(x.Pointer()), interp)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AsTsequenceset is MEOS temporal_as_tsequenceset.
func (x *Temporal) AsTsequenceset(interp functions.Interpolation) (*Temporal, error) {
	_r0, _err := functions.TemporalAsTsequenceset(functions.TemporalFromPointer(x.Pointer()), interp)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AppendTinstant is MEOS temporal_append_tinstant.
func (x *Temporal) AppendTinstant(inst *Temporal, interp functions.Interpolation, maxdist float64, maxt *functions.Interval, expand bool) (*Temporal, error) {
	_r0, _err := functions.TemporalAppendTinstant(functions.TemporalFromPointer(x.Pointer()), functions.TInstantFromPointer(inst.Pointer()), interp, maxdist, maxt, expand)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AppendTsequence is MEOS temporal_append_tsequence.
func (x *Temporal) AppendTsequence(seq *Temporal, expand bool) (*Temporal, error) {
	_r0, _err := functions.TemporalAppendTsequence(functions.TemporalFromPointer(x.Pointer()), functions.TSequenceFromPointer(seq.Pointer()), expand)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// DeleteTimestamptz is MEOS temporal_delete_timestamptz.
func (x *Temporal) DeleteTimestamptz(t int64, connect bool) (*Temporal, error) {
	_r0, _err := functions.TemporalDeleteTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, connect)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// DeleteTstzset is MEOS temporal_delete_tstzset.
func (x *Temporal) DeleteTstzset(s *Set, connect bool) (*Temporal, error) {
	_r0, _err := functions.TemporalDeleteTstzset(functions.TemporalFromPointer(x.Pointer()), functions.SetFromPointer(s.Pointer()), connect)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// DeleteTstzspan is MEOS temporal_delete_tstzspan.
func (x *Temporal) DeleteTstzspan(s *Span, connect bool) (*Temporal, error) {
	_r0, _err := functions.TemporalDeleteTstzspan(functions.TemporalFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()), connect)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// DeleteTstzspanset is MEOS temporal_delete_tstzspanset.
func (x *Temporal) DeleteTstzspanset(ss *SpanSet, connect bool) (*Temporal, error) {
	_r0, _err := functions.TemporalDeleteTstzspanset(functions.TemporalFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss.Pointer()), connect)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Insert is MEOS temporal_insert.
func (x *Temporal) Insert(temp2 *Temporal, connect bool) (*Temporal, error) {
	_r0, _err := functions.TemporalInsert(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()), connect)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Merge is MEOS temporal_merge.
func (x *Temporal) Merge(temp2 *Temporal) (*Temporal, error) {
	_r0, _err := functions.TemporalMerge(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TemporalMergeArray is MEOS temporal_merge_array.
func TemporalMergeArray(temparr unsafe.Pointer, count int) (*Temporal, error) {
	_r0, _err := functions.TemporalMergeArray(temparr, count)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Update is MEOS temporal_update.
func (x *Temporal) Update(temp2 *Temporal, connect bool) (*Temporal, error) {
	_r0, _err := functions.TemporalUpdate(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()), connect)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AfterTimestamptz is MEOS temporal_after_timestamptz.
func (x *Temporal) AfterTimestamptz(t int64, strict bool) (*Temporal, error) {
	_r0, _err := functions.TemporalAfterTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, strict)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtMax is MEOS temporal_at_max.
func (x *Temporal) AtMax() (*Temporal, error) {
	_r0, _err := functions.TemporalAtMax(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtMin is MEOS temporal_at_min.
func (x *Temporal) AtMin() (*Temporal, error) {
	_r0, _err := functions.TemporalAtMin(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtTimestamptz is MEOS temporal_at_timestamptz.
func (x *Temporal) AtTimestamptz(t int64) (*Temporal, error) {
	_r0, _err := functions.TemporalAtTimestamptz(functions.TemporalFromPointer(x.Pointer()), t)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtTstzset is MEOS temporal_at_tstzset.
func (x *Temporal) AtTstzset(s *Set) (*Temporal, error) {
	_r0, _err := functions.TemporalAtTstzset(functions.TemporalFromPointer(x.Pointer()), functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtTstzspan is MEOS temporal_at_tstzspan.
func (x *Temporal) AtTstzspan(s *Span) (*Temporal, error) {
	_r0, _err := functions.TemporalAtTstzspan(functions.TemporalFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtTstzspanset is MEOS temporal_at_tstzspanset.
func (x *Temporal) AtTstzspanset(ss *SpanSet) (*Temporal, error) {
	_r0, _err := functions.TemporalAtTstzspanset(functions.TemporalFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtValues is MEOS temporal_at_values.
func (x *Temporal) AtValues(set *Set) (*Temporal, error) {
	_r0, _err := functions.TemporalAtValues(functions.TemporalFromPointer(x.Pointer()), functions.SetFromPointer(set.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// BeforeTimestamptz is MEOS temporal_before_timestamptz.
func (x *Temporal) BeforeTimestamptz(t int64, strict bool) (*Temporal, error) {
	_r0, _err := functions.TemporalBeforeTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, strict)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusMax is MEOS temporal_minus_max.
func (x *Temporal) MinusMax() (*Temporal, error) {
	_r0, _err := functions.TemporalMinusMax(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusMin is MEOS temporal_minus_min.
func (x *Temporal) MinusMin() (*Temporal, error) {
	_r0, _err := functions.TemporalMinusMin(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusTimestamptz is MEOS temporal_minus_timestamptz.
func (x *Temporal) MinusTimestamptz(t int64) (*Temporal, error) {
	_r0, _err := functions.TemporalMinusTimestamptz(functions.TemporalFromPointer(x.Pointer()), t)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusTstzset is MEOS temporal_minus_tstzset.
func (x *Temporal) MinusTstzset(s *Set) (*Temporal, error) {
	_r0, _err := functions.TemporalMinusTstzset(functions.TemporalFromPointer(x.Pointer()), functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusTstzspan is MEOS temporal_minus_tstzspan.
func (x *Temporal) MinusTstzspan(s *Span) (*Temporal, error) {
	_r0, _err := functions.TemporalMinusTstzspan(functions.TemporalFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusTstzspanset is MEOS temporal_minus_tstzspanset.
func (x *Temporal) MinusTstzspanset(ss *SpanSet) (*Temporal, error) {
	_r0, _err := functions.TemporalMinusTstzspanset(functions.TemporalFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusValues is MEOS temporal_minus_values.
func (x *Temporal) MinusValues(set *Set) (*Temporal, error) {
	_r0, _err := functions.TemporalMinusValues(functions.TemporalFromPointer(x.Pointer()), functions.SetFromPointer(set.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Cmp is MEOS temporal_cmp.
func (x *Temporal) Cmp(temp2 *Temporal) (int, error) {
	_r0, _err := functions.TemporalCmp(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Eq is MEOS temporal_eq.
func (x *Temporal) Eq(temp2 *Temporal) (bool, error) {
	_r0, _err := functions.TemporalEq(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ge is MEOS temporal_ge.
func (x *Temporal) Ge(temp2 *Temporal) (bool, error) {
	_r0, _err := functions.TemporalGe(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Gt is MEOS temporal_gt.
func (x *Temporal) Gt(temp2 *Temporal) (bool, error) {
	_r0, _err := functions.TemporalGt(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Le is MEOS temporal_le.
func (x *Temporal) Le(temp2 *Temporal) (bool, error) {
	_r0, _err := functions.TemporalLe(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Lt is MEOS temporal_lt.
func (x *Temporal) Lt(temp2 *Temporal) (bool, error) {
	_r0, _err := functions.TemporalLt(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ne is MEOS temporal_ne.
func (x *Temporal) Ne(temp2 *Temporal) (bool, error) {
	_r0, _err := functions.TemporalNe(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Spans is MEOS temporal_spans.
func (x *Temporal) Spans(count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.TemporalSpans(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// SplitEachNSpans is MEOS temporal_split_each_n_spans.
func (x *Temporal) SplitEachNSpans(elem_count int, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.TemporalSplitEachNSpans(functions.TemporalFromPointer(x.Pointer()), elem_count, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// SplitNSpans is MEOS temporal_split_n_spans.
func (x *Temporal) SplitNSpans(span_count int, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.TemporalSplitNSpans(functions.TemporalFromPointer(x.Pointer()), span_count, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Derivative is MEOS temporal_derivative.
func (x *Temporal) Derivative() (*Temporal, error) {
	_r0, _err := functions.TemporalDerivative(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// SimplifyDp is MEOS temporal_simplify_dp.
func (x *Temporal) SimplifyDp(dist float64, synchronized bool) (*Temporal, error) {
	_r0, _err := functions.TemporalSimplifyDp(functions.TemporalFromPointer(x.Pointer()), dist, synchronized)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// SimplifyMaxDist is MEOS temporal_simplify_max_dist.
func (x *Temporal) SimplifyMaxDist(dist float64, synchronized bool) (*Temporal, error) {
	_r0, _err := functions.TemporalSimplifyMaxDist(functions.TemporalFromPointer(x.Pointer()), dist, synchronized)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// SimplifyMinDist is MEOS temporal_simplify_min_dist.
func (x *Temporal) SimplifyMinDist(dist float64) (*Temporal, error) {
	_r0, _err := functions.TemporalSimplifyMinDist(functions.TemporalFromPointer(x.Pointer()), dist)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// SimplifyMinTdelta is MEOS temporal_simplify_min_tdelta.
func (x *Temporal) SimplifyMinTdelta(mint *functions.Interval) (*Temporal, error) {
	_r0, _err := functions.TemporalSimplifyMinTdelta(functions.TemporalFromPointer(x.Pointer()), mint)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Tprecision is MEOS temporal_tprecision.
func (x *Temporal) Tprecision(duration *functions.Interval, origin int64) (*Temporal, error) {
	_r0, _err := functions.TemporalTprecision(functions.TemporalFromPointer(x.Pointer()), duration, origin)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Tsample is MEOS temporal_tsample.
func (x *Temporal) Tsample(duration *functions.Interval, origin int64, interp functions.Interpolation) (*Temporal, error) {
	_r0, _err := functions.TemporalTsample(functions.TemporalFromPointer(x.Pointer()), duration, origin, interp)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// DyntimewarpDistance is MEOS temporal_dyntimewarp_distance.
func (x *Temporal) DyntimewarpDistance(temp2 *Temporal) (float64, error) {
	_r0, _err := functions.TemporalDyntimewarpDistance(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// DyntimewarpPath is MEOS temporal_dyntimewarp_path.
func (x *Temporal) DyntimewarpPath(temp2 *Temporal, count unsafe.Pointer) (*functions.Match, error) {
	_r0, _err := functions.TemporalDyntimewarpPath(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// FrechetDistance is MEOS temporal_frechet_distance.
func (x *Temporal) FrechetDistance(temp2 *Temporal) (float64, error) {
	_r0, _err := functions.TemporalFrechetDistance(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// FrechetPath is MEOS temporal_frechet_path.
func (x *Temporal) FrechetPath(temp2 *Temporal, count unsafe.Pointer) (*functions.Match, error) {
	_r0, _err := functions.TemporalFrechetPath(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// HausdorffDistance is MEOS temporal_hausdorff_distance.
func (x *Temporal) HausdorffDistance(temp2 *Temporal) (float64, error) {
	_r0, _err := functions.TemporalHausdorffDistance(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// AverageHausdorffDistance is MEOS temporal_average_hausdorff_distance.
func (x *Temporal) AverageHausdorffDistance(temp2 *Temporal) (float64, error) {
	_r0, _err := functions.TemporalAverageHausdorffDistance(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// LcssDistance is MEOS temporal_lcss_distance.
func (x *Temporal) LcssDistance(temp2 *Temporal, epsilon float64) (float64, error) {
	_r0, _err := functions.TemporalLcssDistance(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()), epsilon)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ExtKalmanFilter is MEOS temporal_ext_kalman_filter.
func (x *Temporal) ExtKalmanFilter(gate float64, q float64, variance float64, to_drop bool) (*Temporal, error) {
	_r0, _err := functions.TemporalExtKalmanFilter(functions.TemporalFromPointer(x.Pointer()), gate, q, variance, to_drop)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TimeBins is MEOS temporal_time_bins.
func (x *Temporal) TimeBins(duration *functions.Interval, origin int64, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.TemporalTimeBins(functions.TemporalFromPointer(x.Pointer()), duration, origin, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// TimeSplit is MEOS temporal_time_split.
func (x *Temporal) TimeSplit(duration *functions.Interval, torigin int64, bins unsafe.Pointer, count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TemporalTimeSplit(functions.TemporalFromPointer(x.Pointer()), duration, torigin, bins, count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}
