package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TFloat struct {
	TNumber
}

// TFloatFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TFloatFromPointer(p unsafe.Pointer) *TFloat {
	if p == nil {
		return nil
	}
	v := &TFloat{}
	v.ptr = p
	return v
}

// TFloatFromMFJSON is MEOS tfloat_from_mfjson.
func TFloatFromMFJSON(str string) (*Temporal, error) {
	_r0, _err := functions.TfloatFromMFJSON(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TFloatIn is MEOS tfloat_in.
func TFloatIn(str string) (*Temporal, error) {
	_r0, _err := functions.TfloatIn(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Out is MEOS tfloat_out.
func (x *TFloat) Out(maxdd int) (string, error) {
	_r0, _err := functions.TfloatOut(functions.TemporalFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TFloatFromBaseTemp is MEOS tfloat_from_base_temp.
func TFloatFromBaseTemp(d float64, temp *Temporal) (*Temporal, error) {
	_r0, _err := functions.TfloatFromBaseTemp(d, functions.TemporalFromPointer(temp.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTint is MEOS tfloat_to_tint.
func (x *TFloat) ToTint() (*Temporal, error) {
	_r0, _err := functions.TfloatToTint(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTbigint is MEOS tfloat_to_tbigint.
func (x *TFloat) ToTbigint() (*Temporal, error) {
	_r0, _err := functions.TfloatToTbigint(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS tfloat_end_value.
func (x *TFloat) EndValue() (float64, error) {
	_r0, _err := functions.TfloatEndValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// MinValue is MEOS tfloat_min_value.
func (x *TFloat) MinValue() (float64, error) {
	_r0, _err := functions.TfloatMinValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// MaxValue is MEOS tfloat_max_value.
func (x *TFloat) MaxValue() (float64, error) {
	_r0, _err := functions.TfloatMaxValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// StartValue is MEOS tfloat_start_value.
func (x *TFloat) StartValue() (float64, error) {
	_r0, _err := functions.TfloatStartValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ValueAtTimestamptz is MEOS tfloat_value_at_timestamptz.
func (x *TFloat) ValueAtTimestamptz(t int64, strict bool) (float64, bool, error) {
	_found, _value, _err := functions.TfloatValueAtTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, strict)
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// ValueN is MEOS tfloat_value_n.
func (x *TFloat) ValueN(n int) (float64, bool, error) {
	_found, _value, _err := functions.TfloatValueN(functions.TemporalFromPointer(x.Pointer()), n)
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Values is MEOS tfloat_values.
func (x *TFloat) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TfloatValues(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Ceil is MEOS tfloat_ceil.
func (x *TFloat) Ceil() (*Temporal, error) {
	_r0, _err := functions.TfloatCeil(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Degrees is MEOS tfloat_degrees.
func (x *TFloat) Degrees(normalize bool) (*Temporal, error) {
	_r0, _err := functions.TfloatDegrees(functions.TemporalFromPointer(x.Pointer()), normalize)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Floor is MEOS tfloat_floor.
func (x *TFloat) Floor() (*Temporal, error) {
	_r0, _err := functions.TfloatFloor(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Radians is MEOS tfloat_radians.
func (x *TFloat) Radians() (*Temporal, error) {
	_r0, _err := functions.TfloatRadians(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ScaleValue is MEOS tfloat_scale_value.
func (x *TFloat) ScaleValue(width float64) (*Temporal, error) {
	_r0, _err := functions.TfloatScaleValue(functions.TemporalFromPointer(x.Pointer()), width)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ShiftScaleValue is MEOS tfloat_shift_scale_value.
func (x *TFloat) ShiftScaleValue(shift float64, width float64) (*Temporal, error) {
	_r0, _err := functions.TfloatShiftScaleValue(functions.TemporalFromPointer(x.Pointer()), shift, width)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ShiftValue is MEOS tfloat_shift_value.
func (x *TFloat) ShiftValue(shift float64) (*Temporal, error) {
	_r0, _err := functions.TfloatShiftValue(functions.TemporalFromPointer(x.Pointer()), shift)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtValue is MEOS tfloat_at_value.
func (x *TFloat) AtValue(d float64) (*Temporal, error) {
	_r0, _err := functions.TfloatAtValue(functions.TemporalFromPointer(x.Pointer()), d)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusValue is MEOS tfloat_minus_value.
func (x *TFloat) MinusValue(d float64) (*Temporal, error) {
	_r0, _err := functions.TfloatMinusValue(functions.TemporalFromPointer(x.Pointer()), d)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Exp is MEOS tfloat_exp.
func (x *TFloat) Exp() (*Temporal, error) {
	_r0, _err := functions.TfloatExp(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Ln is MEOS tfloat_ln.
func (x *TFloat) Ln() (*Temporal, error) {
	_r0, _err := functions.TfloatLn(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Log10 is MEOS tfloat_log10.
func (x *TFloat) Log10() (*Temporal, error) {
	_r0, _err := functions.TfloatLog10(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Sin is MEOS tfloat_sin.
func (x *TFloat) Sin() (*Temporal, error) {
	_r0, _err := functions.TfloatSin(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Cos is MEOS tfloat_cos.
func (x *TFloat) Cos() (*Temporal, error) {
	_r0, _err := functions.TfloatCos(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Tan is MEOS tfloat_tan.
func (x *TFloat) Tan() (*Temporal, error) {
	_r0, _err := functions.TfloatTan(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TimeBoxes is MEOS tfloat_time_boxes.
func (x *TFloat) TimeBoxes(duration *functions.Interval, torigin int64, count unsafe.Pointer) (*TBox, error) {
	_r0, _err := functions.TfloatTimeBoxes(functions.TemporalFromPointer(x.Pointer()), duration, torigin, count)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// ValueBins is MEOS tfloat_value_bins.
func (x *TFloat) ValueBins(vsize float64, vorigin float64, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.TfloatValueBins(functions.TemporalFromPointer(x.Pointer()), vsize, vorigin, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ValueBoxes is MEOS tfloat_value_boxes.
func (x *TFloat) ValueBoxes(vsize float64, vorigin float64, count unsafe.Pointer) (*TBox, error) {
	_r0, _err := functions.TfloatValueBoxes(functions.TemporalFromPointer(x.Pointer()), vsize, vorigin, count)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// ValueSplit is MEOS tfloat_value_split.
func (x *TFloat) ValueSplit(size float64, origin float64, bins unsafe.Pointer, count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TfloatValueSplit(functions.TemporalFromPointer(x.Pointer()), size, origin, bins, count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// ValueTimeBoxes is MEOS tfloat_value_time_boxes.
func (x *TFloat) ValueTimeBoxes(vsize float64, duration *functions.Interval, vorigin float64, torigin int64, count unsafe.Pointer) (*TBox, error) {
	_r0, _err := functions.TfloatValueTimeBoxes(functions.TemporalFromPointer(x.Pointer()), vsize, duration, vorigin, torigin, count)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// ValueTimeSplit is MEOS tfloat_value_time_split.
func (x *TFloat) ValueTimeSplit(vsize float64, duration *functions.Interval, vorigin float64, torigin int64, value_bins unsafe.Pointer, time_bins unsafe.Pointer, count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TfloatValueTimeSplit(functions.TemporalFromPointer(x.Pointer()), vsize, duration, vorigin, torigin, value_bins, time_bins, count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}
