package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

// TGeo is all PostGIS-derived spatiotemporal types (geometry/geography-based). Authoritative parent per MobilityDB manual Ch.7 Figure 7.1 (= the broad C predicate tgeo_type_all). NOTE: the narrower C predicate tgeo_type() and most tgeo_* functions reject points — class membership (manual) is broader than tgeo_* API applicability; see correction OM-M1.

type TGeo struct {
	TSpatial
}

// TGeoFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeoFromPointer(p unsafe.Pointer) *TGeo {
	if p == nil {
		return nil
	}
	v := &TGeo{}
	v.ptr = p
	return v
}

// TGeoFromBaseTemp is MEOS tgeo_from_base_temp.
func TGeoFromBaseTemp(gs *TRGeometrySeqSet, temp *Temporal) (*Temporal, error) {
	_r0, _err := functions.TgeoFromBaseTemp(functions.GeomFromPointer(gs.Pointer()), functions.TemporalFromPointer(temp.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Centroid is MEOS tgeo_centroid.
func (x *TGeo) Centroid() (*Temporal, error) {
	_r0, _err := functions.TgeoCentroid(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ConvexHull is MEOS tgeo_convex_hull.
func (x *TGeo) ConvexHull() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TgeoConvexHull(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS tgeo_end_value.
func (x *TGeo) EndValue() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TgeoEndValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// StartValue is MEOS tgeo_start_value.
func (x *TGeo) StartValue() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TgeoStartValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// TraversedArea is MEOS tgeo_traversed_area.
func (x *TGeo) TraversedArea(unary_union bool) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TgeoTraversedArea(functions.TemporalFromPointer(x.Pointer()), unary_union)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// ValueAtTimestamptz is MEOS tgeo_value_at_timestamptz.
func (x *TGeo) ValueAtTimestamptz(t int64, strict bool) (*TRGeometrySeqSet, bool, error) {
	_found, _value, _err := functions.TgeoValueAtTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, strict)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return TRGeometrySeqSetFromPointer(_value.Pointer()), true, nil
}

// ValueN is MEOS tgeo_value_n.
func (x *TGeo) ValueN(n int) (*TRGeometrySeqSet, bool, error) {
	_found, _value, _err := functions.TgeoValueN(functions.TemporalFromPointer(x.Pointer()), n)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return TRGeometrySeqSetFromPointer(_value.Pointer()), true, nil
}

// Values is MEOS tgeo_values.
func (x *TGeo) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TgeoValues(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Affine is MEOS tgeo_affine.
func (x *TGeo) Affine(a *functions.AFFINE) (*Temporal, error) {
	_r0, _err := functions.TgeoAffine(functions.TemporalFromPointer(x.Pointer()), a)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Scale is MEOS tgeo_scale.
func (x *TGeo) Scale(scale *TRGeometrySeqSet, sorigin *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TgeoScale(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(scale.Pointer()), functions.GeomFromPointer(sorigin.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtGeom is MEOS tgeo_at_geom.
func (x *TGeo) AtGeom(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TgeoAtGeom(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtStbox is MEOS tgeo_at_stbox.
func (x *TGeo) AtStbox(box *STBox, border_inc bool) (*Temporal, error) {
	_r0, _err := functions.TgeoAtSTBOX(functions.TemporalFromPointer(x.Pointer()), functions.STBoxFromPointer(box.Pointer()), border_inc)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtValue is MEOS tgeo_at_value.
func (x *TGeo) AtValue(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TgeoAtValue(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusGeom is MEOS tgeo_minus_geom.
func (x *TGeo) MinusGeom(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TgeoMinusGeom(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusStbox is MEOS tgeo_minus_stbox.
func (x *TGeo) MinusStbox(box *STBox, border_inc bool) (*Temporal, error) {
	_r0, _err := functions.TgeoMinusSTBOX(functions.TemporalFromPointer(x.Pointer()), functions.STBoxFromPointer(box.Pointer()), border_inc)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusValue is MEOS tgeo_minus_value.
func (x *TGeo) MinusValue(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TgeoMinusValue(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Stboxes is MEOS tgeo_stboxes.
func (x *TGeo) Stboxes(count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.TgeoStboxes(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// SpaceBoxes is MEOS tgeo_space_boxes.
func (x *TGeo) SpaceBoxes(xsize float64, ysize float64, zsize float64, sorigin *TRGeometrySeqSet, bitmatrix bool, border_inc bool, count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.TgeoSpaceBoxes(functions.TemporalFromPointer(x.Pointer()), xsize, ysize, zsize, functions.GeomFromPointer(sorigin.Pointer()), bitmatrix, border_inc, count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// SpaceTimeBoxes is MEOS tgeo_space_time_boxes.
func (x *TGeo) SpaceTimeBoxes(xsize float64, ysize float64, zsize float64, duration *functions.Interval, sorigin *TRGeometrySeqSet, torigin int64, bitmatrix bool, border_inc bool, count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.TgeoSpaceTimeBoxes(functions.TemporalFromPointer(x.Pointer()), xsize, ysize, zsize, duration, functions.GeomFromPointer(sorigin.Pointer()), torigin, bitmatrix, border_inc, count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// SplitEachNStboxes is MEOS tgeo_split_each_n_stboxes.
func (x *TGeo) SplitEachNStboxes(elem_count int, count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.TgeoSplitEachNStboxes(functions.TemporalFromPointer(x.Pointer()), elem_count, count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// SplitNStboxes is MEOS tgeo_split_n_stboxes.
func (x *TGeo) SplitNStboxes(box_count int, count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.TgeoSplitNStboxes(functions.TemporalFromPointer(x.Pointer()), box_count, count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}
