package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TInt struct {
	TNumber
}

// TIntFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TIntFromPointer(p unsafe.Pointer) *TInt {
	if p == nil {
		return nil
	}
	v := &TInt{}
	v.ptr = p
	return v
}

// TIntFromMFJSON is MEOS tint_from_mfjson.
func TIntFromMFJSON(str string) (*Temporal, error) {
	_r0, _err := functions.TintFromMFJSON(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TIntIn is MEOS tint_in.
func TIntIn(str string) (*Temporal, error) {
	_r0, _err := functions.TintIn(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Out is MEOS tint_out.
func (x *TInt) Out() (string, error) {
	_r0, _err := functions.TintOut(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TIntFromBaseTemp is MEOS tint_from_base_temp.
func TIntFromBaseTemp(i int, temp *Temporal) (*Temporal, error) {
	_r0, _err := functions.TintFromBaseTemp(i, functions.TemporalFromPointer(temp.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTfloat is MEOS tint_to_tfloat.
func (x *TInt) ToTfloat() (*Temporal, error) {
	_r0, _err := functions.TintToTfloat(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTbigint is MEOS tint_to_tbigint.
func (x *TInt) ToTbigint() (*Temporal, error) {
	_r0, _err := functions.TintToTbigint(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS tint_end_value.
func (x *TInt) EndValue() (int, error) {
	_r0, _err := functions.TintEndValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// MaxValue is MEOS tint_max_value.
func (x *TInt) MaxValue() (int, error) {
	_r0, _err := functions.TintMaxValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// MinValue is MEOS tint_min_value.
func (x *TInt) MinValue() (int, error) {
	_r0, _err := functions.TintMinValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// StartValue is MEOS tint_start_value.
func (x *TInt) StartValue() (int, error) {
	_r0, _err := functions.TintStartValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ValueAtTimestamptz is MEOS tint_value_at_timestamptz.
func (x *TInt) ValueAtTimestamptz(t int64, strict bool) (int, bool, error) {
	_found, _value, _err := functions.TintValueAtTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, strict)
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// ValueN is MEOS tint_value_n.
func (x *TInt) ValueN(n int) (int, bool, error) {
	_found, _value, _err := functions.TintValueN(functions.TemporalFromPointer(x.Pointer()), n)
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Values is MEOS tint_values.
func (x *TInt) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TintValues(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// ScaleValue is MEOS tint_scale_value.
func (x *TInt) ScaleValue(width int) (*Temporal, error) {
	_r0, _err := functions.TintScaleValue(functions.TemporalFromPointer(x.Pointer()), width)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ShiftScaleValue is MEOS tint_shift_scale_value.
func (x *TInt) ShiftScaleValue(shift int, width int) (*Temporal, error) {
	_r0, _err := functions.TintShiftScaleValue(functions.TemporalFromPointer(x.Pointer()), shift, width)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ShiftValue is MEOS tint_shift_value.
func (x *TInt) ShiftValue(shift int) (*Temporal, error) {
	_r0, _err := functions.TintShiftValue(functions.TemporalFromPointer(x.Pointer()), shift)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtValue is MEOS tint_at_value.
func (x *TInt) AtValue(i int) (*Temporal, error) {
	_r0, _err := functions.TintAtValue(functions.TemporalFromPointer(x.Pointer()), i)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusValue is MEOS tint_minus_value.
func (x *TInt) MinusValue(i int) (*Temporal, error) {
	_r0, _err := functions.TintMinusValue(functions.TemporalFromPointer(x.Pointer()), i)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TimeBoxes is MEOS tint_time_boxes.
func (x *TInt) TimeBoxes(duration *functions.Interval, torigin int64, count unsafe.Pointer) (*TBox, error) {
	_r0, _err := functions.TintTimeBoxes(functions.TemporalFromPointer(x.Pointer()), duration, torigin, count)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// ValueBins is MEOS tint_value_bins.
func (x *TInt) ValueBins(vsize int, vorigin int, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.TintValueBins(functions.TemporalFromPointer(x.Pointer()), vsize, vorigin, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ValueBoxes is MEOS tint_value_boxes.
func (x *TInt) ValueBoxes(vsize int, vorigin int, count unsafe.Pointer) (*TBox, error) {
	_r0, _err := functions.TintValueBoxes(functions.TemporalFromPointer(x.Pointer()), vsize, vorigin, count)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// ValueSplit is MEOS tint_value_split.
func (x *TInt) ValueSplit(vsize int, vorigin int, bins unsafe.Pointer, count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TintValueSplit(functions.TemporalFromPointer(x.Pointer()), vsize, vorigin, bins, count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// ValueTimeBoxes is MEOS tint_value_time_boxes.
func (x *TInt) ValueTimeBoxes(vsize int, duration *functions.Interval, vorigin int, torigin int64, count unsafe.Pointer) (*TBox, error) {
	_r0, _err := functions.TintValueTimeBoxes(functions.TemporalFromPointer(x.Pointer()), vsize, duration, vorigin, torigin, count)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// ValueTimeSplit is MEOS tint_value_time_split.
func (x *TInt) ValueTimeSplit(size int, duration *functions.Interval, vorigin int, torigin int64, value_bins unsafe.Pointer, time_bins unsafe.Pointer, count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TintValueTimeSplit(functions.TemporalFromPointer(x.Pointer()), size, duration, vorigin, torigin, value_bins, time_bins, count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}
