package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TRGeometry struct {
	TSpatial
}

// TRGeometryFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TRGeometryFromPointer(p unsafe.Pointer) *TRGeometry {
	if p == nil {
		return nil
	}
	v := &TRGeometry{}
	v.ptr = p
	return v
}

// TRGeometryIn is MEOS trgeometry_in.
func TRGeometryIn(str string) (*Temporal, error) {
	_r0, _err := functions.TrgeometryIn(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TRGeometryFromMFJSON is MEOS trgeometry_from_mfjson.
func TRGeometryFromMFJSON(mfjson string) (*Temporal, error) {
	_r0, _err := functions.TrgeometryFromMFJSON(mfjson)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Out is MEOS trgeometry_out.
func (x *TRGeometry) Out() (string, error) {
	_r0, _err := functions.TrgeometryOut(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsText is MEOS trgeometry_as_text.
func (x *TRGeometry) AsText(maxdd int) (string, error) {
	_r0, _err := functions.TrgeometryAsText(functions.TemporalFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsEWKT is MEOS trgeometry_as_ewkt.
func (x *TRGeometry) AsEWKT(maxdd int) (string, error) {
	_r0, _err := functions.TrgeometryAsEWKT(functions.TemporalFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// ToTpose is MEOS trgeometry_to_tpose.
func (x *TRGeometry) ToTpose() (*Temporal, error) {
	_r0, _err := functions.TrgeometryToTpose(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTgeompoint is MEOS trgeometry_to_tgeompoint.
func (x *TRGeometry) ToTgeompoint() (*Temporal, error) {
	_r0, _err := functions.TrgeometryToTgeompoint(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTgeometry is MEOS trgeometry_to_tgeometry.
func (x *TRGeometry) ToTgeometry() (*Temporal, error) {
	_r0, _err := functions.TrgeometryToTgeometry(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// EndInstant is MEOS trgeometry_end_instant.
func (x *TRGeometry) EndInstant() (*Temporal, error) {
	_r0, _err := functions.TrgeometryEndInstant(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// EndSequence is MEOS trgeometry_end_sequence.
func (x *TRGeometry) EndSequence() (*Temporal, error) {
	_r0, _err := functions.TrgeometryEndSequence(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS trgeometry_end_value.
func (x *TRGeometry) EndValue() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TrgeometryEndValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// Geom is MEOS trgeometry_geom.
func (x *TRGeometry) Geom() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TrgeometryGeom(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// InstantN is MEOS trgeometry_instant_n.
func (x *TRGeometry) InstantN(n int) (*Temporal, error) {
	_r0, _err := functions.TrgeometryInstantN(functions.TemporalFromPointer(x.Pointer()), n)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Instants is MEOS trgeometry_instants.
func (x *TRGeometry) Instants(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TrgeometryInstants(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Points is MEOS trgeometry_points.
func (x *TRGeometry) Points() (*Set, error) {
	_r0, _err := functions.TrgeometryPoints(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Yaw is MEOS trgeometry_yaw.
func (x *TRGeometry) Yaw() (*Temporal, error) {
	_r0, _err := functions.TrgeometryYaw(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Pitch is MEOS trgeometry_pitch.
func (x *TRGeometry) Pitch() (*Temporal, error) {
	_r0, _err := functions.TrgeometryPitch(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Roll is MEOS trgeometry_roll.
func (x *TRGeometry) Roll() (*Temporal, error) {
	_r0, _err := functions.TrgeometryRoll(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Segments is MEOS trgeometry_segments.
func (x *TRGeometry) Segments(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TrgeometrySegments(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// SequenceN is MEOS trgeometry_sequence_n.
func (x *TRGeometry) SequenceN(i int) (*Temporal, error) {
	_r0, _err := functions.TrgeometrySequenceN(functions.TemporalFromPointer(x.Pointer()), i)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Sequences is MEOS trgeometry_sequences.
func (x *TRGeometry) Sequences(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TrgeometrySequences(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// StartInstant is MEOS trgeometry_start_instant.
func (x *TRGeometry) StartInstant() (*Temporal, error) {
	_r0, _err := functions.TrgeometryStartInstant(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// StartSequence is MEOS trgeometry_start_sequence.
func (x *TRGeometry) StartSequence() (*Temporal, error) {
	_r0, _err := functions.TrgeometryStartSequence(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// StartValue is MEOS trgeometry_start_value.
func (x *TRGeometry) StartValue() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TrgeometryStartValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// ValueN is MEOS trgeometry_value_n.
func (x *TRGeometry) ValueN(n int) (*TRGeometrySeqSet, bool, error) {
	_found, _value, _err := functions.TrgeometryValueN(functions.TemporalFromPointer(x.Pointer()), n)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return TRGeometrySeqSetFromPointer(_value.Pointer()), true, nil
}

// TraversedArea is MEOS trgeometry_traversed_area.
func (x *TRGeometry) TraversedArea(unary_union bool) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TrgeometryTraversedArea(functions.TemporalFromPointer(x.Pointer()), unary_union)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// Centroid is MEOS trgeometry_centroid.
func (x *TRGeometry) Centroid() (*Temporal, error) {
	_r0, _err := functions.TrgeometryCentroid(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ConvexHull is MEOS trgeometry_convex_hull.
func (x *TRGeometry) ConvexHull() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TrgeometryConvexHull(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// BodyPointTrajectory is MEOS trgeometry_body_point_trajectory.
func (x *TRGeometry) BodyPointTrajectory(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TrgeometryBodyPointTrajectory(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// SpaceBoxes is MEOS trgeometry_space_boxes.
func (x *TRGeometry) SpaceBoxes(xsize float64, ysize float64, zsize float64, sorigin *TRGeometrySeqSet, bitmatrix bool, border_inc bool, count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.TrgeometrySpaceBoxes(functions.TemporalFromPointer(x.Pointer()), xsize, ysize, zsize, functions.GeomFromPointer(sorigin.Pointer()), bitmatrix, border_inc, count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// SpaceTimeBoxes is MEOS trgeometry_space_time_boxes.
func (x *TRGeometry) SpaceTimeBoxes(xsize float64, ysize float64, zsize float64, duration *functions.Interval, sorigin *TRGeometrySeqSet, torigin int64, bitmatrix bool, border_inc bool, count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.TrgeometrySpaceTimeBoxes(functions.TemporalFromPointer(x.Pointer()), xsize, ysize, zsize, duration, functions.GeomFromPointer(sorigin.Pointer()), torigin, bitmatrix, border_inc, count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// Stboxes is MEOS trgeometry_stboxes.
func (x *TRGeometry) Stboxes(count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.TrgeometryStboxes(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// SplitNStboxes is MEOS trgeometry_split_n_stboxes.
func (x *TRGeometry) SplitNStboxes(box_count int, count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.TrgeometrySplitNStboxes(functions.TemporalFromPointer(x.Pointer()), box_count, count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// SplitEachNStboxes is MEOS trgeometry_split_each_n_stboxes.
func (x *TRGeometry) SplitEachNStboxes(elem_count int, count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.TrgeometrySplitEachNStboxes(functions.TemporalFromPointer(x.Pointer()), elem_count, count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// HausdorffDistance is MEOS trgeometry_hausdorff_distance.
func (x *TRGeometry) HausdorffDistance(temp2 *Temporal) (float64, error) {
	_r0, _err := functions.TrgeometryHausdorffDistance(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// FrechetDistance is MEOS trgeometry_frechet_distance.
func (x *TRGeometry) FrechetDistance(temp2 *Temporal) (float64, error) {
	_r0, _err := functions.TrgeometryFrechetDistance(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// DyntimewarpDistance is MEOS trgeometry_dyntimewarp_distance.
func (x *TRGeometry) DyntimewarpDistance(temp2 *Temporal) (float64, error) {
	_r0, _err := functions.TrgeometryDyntimewarpDistance(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// FrechetPath is MEOS trgeometry_frechet_path.
func (x *TRGeometry) FrechetPath(temp2 *Temporal, count unsafe.Pointer) (*functions.Match, error) {
	_r0, _err := functions.TrgeometryFrechetPath(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// DyntimewarpPath is MEOS trgeometry_dyntimewarp_path.
func (x *TRGeometry) DyntimewarpPath(temp2 *Temporal, count unsafe.Pointer) (*functions.Match, error) {
	_r0, _err := functions.TrgeometryDyntimewarpPath(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Length is MEOS trgeometry_length.
func (x *TRGeometry) Length() (float64, error) {
	_r0, _err := functions.TrgeometryLength(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// CumulativeLength is MEOS trgeometry_cumulative_length.
func (x *TRGeometry) CumulativeLength() (*Temporal, error) {
	_r0, _err := functions.TrgeometryCumulativeLength(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AngularSpeed is MEOS trgeometry_angular_speed.
func (x *TRGeometry) AngularSpeed() (*Temporal, error) {
	_r0, _err := functions.TrgeometryAngularSpeed(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Speed is MEOS trgeometry_speed.
func (x *TRGeometry) Speed() (*Temporal, error) {
	_r0, _err := functions.TrgeometrySpeed(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Twcentroid is MEOS trgeometry_twcentroid.
func (x *TRGeometry) Twcentroid() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TrgeometryTwcentroid(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// AppendTinstant is MEOS trgeometry_append_tinstant.
func (x *TRGeometry) AppendTinstant(inst *Temporal, interp functions.Interpolation, maxdist float64, maxt *functions.Interval, expand bool) (*Temporal, error) {
	_r0, _err := functions.TrgeometryAppendTinstant(functions.TemporalFromPointer(x.Pointer()), functions.TInstantFromPointer(inst.Pointer()), interp, maxdist, maxt, expand)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AppendTsequence is MEOS trgeometry_append_tsequence.
func (x *TRGeometry) AppendTsequence(seq *Temporal, expand bool) (*Temporal, error) {
	_r0, _err := functions.TrgeometryAppendTsequence(functions.TemporalFromPointer(x.Pointer()), functions.TSequenceFromPointer(seq.Pointer()), expand)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// DeleteTimestamptz is MEOS trgeometry_delete_timestamptz.
func (x *TRGeometry) DeleteTimestamptz(t int64, connect bool) (*Temporal, error) {
	_r0, _err := functions.TrgeometryDeleteTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, connect)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// DeleteTstzset is MEOS trgeometry_delete_tstzset.
func (x *TRGeometry) DeleteTstzset(s *Set, connect bool) (*Temporal, error) {
	_r0, _err := functions.TrgeometryDeleteTstzset(functions.TemporalFromPointer(x.Pointer()), functions.SetFromPointer(s.Pointer()), connect)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// DeleteTstzspan is MEOS trgeometry_delete_tstzspan.
func (x *TRGeometry) DeleteTstzspan(s *Span, connect bool) (*Temporal, error) {
	_r0, _err := functions.TrgeometryDeleteTstzspan(functions.TemporalFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()), connect)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// DeleteTstzspanset is MEOS trgeometry_delete_tstzspanset.
func (x *TRGeometry) DeleteTstzspanset(ss *SpanSet, connect bool) (*Temporal, error) {
	_r0, _err := functions.TrgeometryDeleteTstzspanset(functions.TemporalFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss.Pointer()), connect)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Merge is MEOS trgeometry_merge.
func (x *TRGeometry) Merge(temp2 *Temporal) (*Temporal, error) {
	_r0, _err := functions.TrgeometryMerge(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(temp2.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TRGeometryMergeArray is MEOS trgeometry_merge_array.
func TRGeometryMergeArray(temparr unsafe.Pointer, count int) (*Temporal, error) {
	_r0, _err := functions.TrgeometryMergeArray(temparr, count)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Round is MEOS trgeometry_round.
func (x *TRGeometry) Round(maxdd int) (*Temporal, error) {
	_r0, _err := functions.TrgeometryRound(functions.TemporalFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// SetInterp is MEOS trgeometry_set_interp.
func (x *TRGeometry) SetInterp(interp functions.Interpolation) (*Temporal, error) {
	_r0, _err := functions.TrgeometrySetInterp(functions.TemporalFromPointer(x.Pointer()), interp)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AsTinstant is MEOS trgeometry_as_tinstant.
func (x *TRGeometry) AsTinstant() (*Temporal, error) {
	_r0, _err := functions.TrgeometryAsTinstant(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AsTsequence is MEOS trgeometry_as_tsequence.
func (x *TRGeometry) AsTsequence(interp_str string) (*Temporal, error) {
	_r0, _err := functions.TrgeometryAsTsequence(functions.TemporalFromPointer(x.Pointer()), interp_str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AsTsequenceset is MEOS trgeometry_as_tsequenceset.
func (x *TRGeometry) AsTsequenceset(interp_str string) (*Temporal, error) {
	_r0, _err := functions.TrgeometryAsTsequenceset(functions.TemporalFromPointer(x.Pointer()), interp_str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AfterTimestamptz is MEOS trgeometry_after_timestamptz.
func (x *TRGeometry) AfterTimestamptz(t int64, strict bool) (*Temporal, error) {
	_r0, _err := functions.TrgeometryAfterTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, strict)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// BeforeTimestamptz is MEOS trgeometry_before_timestamptz.
func (x *TRGeometry) BeforeTimestamptz(t int64, strict bool) (*Temporal, error) {
	_r0, _err := functions.TrgeometryBeforeTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, strict)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtGeom is MEOS trgeometry_at_geom.
func (x *TRGeometry) AtGeom(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TrgeometryAtGeom(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusGeom is MEOS trgeometry_minus_geom.
func (x *TRGeometry) MinusGeom(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TrgeometryMinusGeom(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtStbox is MEOS trgeometry_at_stbox.
func (x *TRGeometry) AtStbox(box *STBox, border_inc bool) (*Temporal, error) {
	_r0, _err := functions.TrgeometryAtSTBOX(functions.TemporalFromPointer(x.Pointer()), functions.STBoxFromPointer(box.Pointer()), border_inc)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusStbox is MEOS trgeometry_minus_stbox.
func (x *TRGeometry) MinusStbox(box *STBox, border_inc bool) (*Temporal, error) {
	_r0, _err := functions.TrgeometryMinusSTBOX(functions.TemporalFromPointer(x.Pointer()), functions.STBoxFromPointer(box.Pointer()), border_inc)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtValue is MEOS trgeometry_at_value.
func (x *TRGeometry) AtValue(pose *Pose) (*Temporal, error) {
	_r0, _err := functions.TrgeometryAtValue(functions.TemporalFromPointer(x.Pointer()), functions.PoseFromPointer(pose.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusValue is MEOS trgeometry_minus_value.
func (x *TRGeometry) MinusValue(pose *Pose) (*Temporal, error) {
	_r0, _err := functions.TrgeometryMinusValue(functions.TemporalFromPointer(x.Pointer()), functions.PoseFromPointer(pose.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtValues is MEOS trgeometry_at_values.
func (x *TRGeometry) AtValues(s *Set) (*Temporal, error) {
	_r0, _err := functions.TrgeometryAtValues(functions.TemporalFromPointer(x.Pointer()), functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusValues is MEOS trgeometry_minus_values.
func (x *TRGeometry) MinusValues(s *Set) (*Temporal, error) {
	_r0, _err := functions.TrgeometryMinusValues(functions.TemporalFromPointer(x.Pointer()), functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtTimestamptz is MEOS trgeometry_at_timestamptz.
func (x *TRGeometry) AtTimestamptz(t int64) (*Temporal, error) {
	_r0, _err := functions.TrgeometryAtTimestamptz(functions.TemporalFromPointer(x.Pointer()), t)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusTimestamptz is MEOS trgeometry_minus_timestamptz.
func (x *TRGeometry) MinusTimestamptz(t int64) (*Temporal, error) {
	_r0, _err := functions.TrgeometryMinusTimestamptz(functions.TemporalFromPointer(x.Pointer()), t)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtTstzset is MEOS trgeometry_at_tstzset.
func (x *TRGeometry) AtTstzset(s *Set) (*Temporal, error) {
	_r0, _err := functions.TrgeometryAtTstzset(functions.TemporalFromPointer(x.Pointer()), functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusTstzset is MEOS trgeometry_minus_tstzset.
func (x *TRGeometry) MinusTstzset(s *Set) (*Temporal, error) {
	_r0, _err := functions.TrgeometryMinusTstzset(functions.TemporalFromPointer(x.Pointer()), functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtTstzspan is MEOS trgeometry_at_tstzspan.
func (x *TRGeometry) AtTstzspan(s *Span) (*Temporal, error) {
	_r0, _err := functions.TrgeometryAtTstzspan(functions.TemporalFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusTstzspan is MEOS trgeometry_minus_tstzspan.
func (x *TRGeometry) MinusTstzspan(s *Span) (*Temporal, error) {
	_r0, _err := functions.TrgeometryMinusTstzspan(functions.TemporalFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtTstzspanset is MEOS trgeometry_at_tstzspanset.
func (x *TRGeometry) AtTstzspanset(ss *SpanSet) (*Temporal, error) {
	_r0, _err := functions.TrgeometryAtTstzspanset(functions.TemporalFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusTstzspanset is MEOS trgeometry_minus_tstzspanset.
func (x *TRGeometry) MinusTstzspanset(ss *SpanSet) (*Temporal, error) {
	_r0, _err := functions.TrgeometryMinusTstzspanset(functions.TemporalFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtElevation is MEOS trgeometry_at_elevation.
func (x *TRGeometry) AtElevation(s *Span) (*Temporal, error) {
	_r0, _err := functions.TrgeometryAtElevation(functions.TemporalFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusElevation is MEOS trgeometry_minus_elevation.
func (x *TRGeometry) MinusElevation(s *Span) (*Temporal, error) {
	_r0, _err := functions.TrgeometryMinusElevation(functions.TemporalFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
