package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TRGeometrySeqSet struct {
	handle
}

// TRGeometrySeqSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TRGeometrySeqSetFromPointer(p unsafe.Pointer) *TRGeometrySeqSet {
	if p == nil {
		return nil
	}
	v := &TRGeometrySeqSet{}
	v.ptr = p
	return v
}

// Make is MEOS trgeometryseqset_make.
func (x *TRGeometrySeqSet) Make(sequences unsafe.Pointer, count int, normalize bool) (*Temporal, error) {
	_r0, _err := functions.TrgeometryseqsetMake(functions.GeomFromPointer(x.Pointer()), sequences, count, normalize)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MakeGaps is MEOS trgeometryseqset_make_gaps.
func (x *TRGeometrySeqSet) MakeGaps(instants unsafe.Pointer, count int, interp functions.Interpolation, maxt *functions.Interval, maxdist float64) (*Temporal, error) {
	_r0, _err := functions.TrgeometryseqsetMakeGaps(functions.GeomFromPointer(x.Pointer()), instants, count, interp, maxt, maxdist)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
