package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TSequenceSet struct {
	Temporal
}

// TSequenceSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TSequenceSetFromPointer(p unsafe.Pointer) *TSequenceSet {
	if p == nil {
		return nil
	}
	v := &TSequenceSet{}
	v.ptr = p
	return v
}

// TSequenceSetMake is MEOS tsequenceset_make.
func TSequenceSetMake(sequences unsafe.Pointer, count int, normalize bool) (*Temporal, error) {
	_r0, _err := functions.TsequencesetMake(sequences, count, normalize)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TSequenceSetMakeGaps is MEOS tsequenceset_make_gaps.
func TSequenceSetMakeGaps(instants unsafe.Pointer, count int, interp functions.Interpolation, maxt *functions.Interval, maxdist float64) (*Temporal, error) {
	_r0, _err := functions.TsequencesetMakeGaps(instants, count, interp, maxt, maxdist)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
