package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TsTzSpanSet struct {
	SpanSet
}

// TsTzSpanSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TsTzSpanSetFromPointer(p unsafe.Pointer) *TsTzSpanSet {
	if p == nil {
		return nil
	}
	v := &TsTzSpanSet{}
	v.ptr = p
	return v
}

// TsTzSpanSetIn is MEOS tstzspanset_in.
func TsTzSpanSetIn(str string) (*SpanSet, error) {
	_r0, _err := functions.TstzspansetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Out is MEOS tstzspanset_out.
func (x *TsTzSpanSet) Out() (string, error) {
	_r0, _err := functions.TstzspansetOut(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// ToDatespanset is MEOS tstzspanset_to_datespanset.
func (x *TsTzSpanSet) ToDatespanset() (*SpanSet, error) {
	_r0, _err := functions.TstzspansetToDatespanset(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Duration is MEOS tstzspanset_duration.
func (x *TsTzSpanSet) Duration(boundspan bool) (*functions.Interval, error) {
	_r0, _err := functions.TstzspansetDuration(functions.SpanSetFromPointer(x.Pointer()), boundspan)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// EndTimestamptz is MEOS tstzspanset_end_timestamptz.
func (x *TsTzSpanSet) EndTimestamptz() (int64, error) {
	_r0, _err := functions.TstzspansetEndTimestamptz(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Lower is MEOS tstzspanset_lower.
func (x *TsTzSpanSet) Lower() (int64, error) {
	_r0, _err := functions.TstzspansetLower(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// NumTimestamps is MEOS tstzspanset_num_timestamps.
func (x *TsTzSpanSet) NumTimestamps() (int, error) {
	_r0, _err := functions.TstzspansetNumTimestamps(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// StartTimestamptz is MEOS tstzspanset_start_timestamptz.
func (x *TsTzSpanSet) StartTimestamptz() (int64, error) {
	_r0, _err := functions.TstzspansetStartTimestamptz(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Timestamps is MEOS tstzspanset_timestamps.
func (x *TsTzSpanSet) Timestamps() (*Set, error) {
	_r0, _err := functions.TstzspansetTimestamps(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// TimestamptzN is MEOS tstzspanset_timestamptz_n.
func (x *TsTzSpanSet) TimestamptzN(n int) (int64, bool, error) {
	_found, _value, _err := functions.TstzspansetTimestamptzN(functions.SpanSetFromPointer(x.Pointer()), n)
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Upper is MEOS tstzspanset_upper.
func (x *TsTzSpanSet) Upper() (int64, error) {
	_r0, _err := functions.TstzspansetUpper(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ShiftScale is MEOS tstzspanset_shift_scale.
func (x *TsTzSpanSet) ShiftScale(shift *functions.Interval, duration *functions.Interval) (*SpanSet, error) {
	_r0, _err := functions.TstzspansetShiftScale(functions.SpanSetFromPointer(x.Pointer()), shift, duration)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Tprecision is MEOS tstzspanset_tprecision.
func (x *TsTzSpanSet) Tprecision(duration *functions.Interval, torigin int64) (*SpanSet, error) {
	_r0, _err := functions.TstzspansetTprecision(functions.SpanSetFromPointer(x.Pointer()), duration, torigin)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Bins is MEOS tstzspanset_bins.
func (x *TsTzSpanSet) Bins(duration *functions.Interval, torigin int64, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.TstzspansetBins(functions.SpanSetFromPointer(x.Pointer()), duration, torigin, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToStbox is MEOS tstzspanset_to_stbox.
func (x *TsTzSpanSet) ToStbox() (*STBox, error) {
	_r0, _err := functions.TstzspansetToSTBOX(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}
