package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TsTzSpan struct {
	Span
}

// TsTzSpanFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TsTzSpanFromPointer(p unsafe.Pointer) *TsTzSpan {
	if p == nil {
		return nil
	}
	v := &TsTzSpan{}
	v.ptr = p
	return v
}

// TsTzSpanIn is MEOS tstzspan_in.
func TsTzSpanIn(str string) (*Span, error) {
	_r0, _err := functions.TstzspanIn(str)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Out is MEOS tstzspan_out.
func (x *TsTzSpan) Out() (string, error) {
	_r0, _err := functions.TstzspanOut(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TsTzSpanMake is MEOS tstzspan_make.
func TsTzSpanMake(lower int64, upper int64, lower_inc bool, upper_inc bool) (*Span, error) {
	_r0, _err := functions.TstzspanMake(lower, upper, lower_inc, upper_inc)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToDatespan is MEOS tstzspan_to_datespan.
func (x *TsTzSpan) ToDatespan() (*Span, error) {
	_r0, _err := functions.TstzspanToDatespan(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Duration is MEOS tstzspan_duration.
func (x *TsTzSpan) Duration() (*functions.Interval, error) {
	_r0, _err := functions.TstzspanDuration(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Lower is MEOS tstzspan_lower.
func (x *TsTzSpan) Lower() (int64, error) {
	_r0, _err := functions.TstzspanLower(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Upper is MEOS tstzspan_upper.
func (x *TsTzSpan) Upper() (int64, error) {
	_r0, _err := functions.TstzspanUpper(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Expand is MEOS tstzspan_expand.
func (x *TsTzSpan) Expand(interv *functions.Interval) (*Span, error) {
	_r0, _err := functions.TstzspanExpand(functions.SpanFromPointer(x.Pointer()), interv)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ShiftScale is MEOS tstzspan_shift_scale.
func (x *TsTzSpan) ShiftScale(shift *functions.Interval, duration *functions.Interval) (*Span, error) {
	_r0, _err := functions.TstzspanShiftScale(functions.SpanFromPointer(x.Pointer()), shift, duration)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Tprecision is MEOS tstzspan_tprecision.
func (x *TsTzSpan) Tprecision(duration *functions.Interval, torigin int64) (*Span, error) {
	_r0, _err := functions.TstzspanTprecision(functions.SpanFromPointer(x.Pointer()), duration, torigin)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Bins is MEOS tstzspan_bins.
func (x *TsTzSpan) Bins(duration *functions.Interval, origin int64, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.TstzspanBins(functions.SpanFromPointer(x.Pointer()), duration, origin, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToStbox is MEOS tstzspan_to_stbox.
func (x *TsTzSpan) ToStbox() (*STBox, error) {
	_r0, _err := functions.TstzspanToSTBOX(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}
