package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TsTzSet struct {
	Set
}

// TsTzSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TsTzSetFromPointer(p unsafe.Pointer) *TsTzSet {
	if p == nil {
		return nil
	}
	v := &TsTzSet{}
	v.ptr = p
	return v
}

// TsTzSetIn is MEOS tstzset_in.
func TsTzSetIn(str string) (*Set, error) {
	_r0, _err := functions.TstzsetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Out is MEOS tstzset_out.
func (x *TsTzSet) Out() (string, error) {
	_r0, _err := functions.TstzsetOut(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TsTzSetMake is MEOS tstzset_make.
func TsTzSetMake(values unsafe.Pointer, count int) (*Set, error) {
	_r0, _err := functions.TstzsetMake(values, count)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// ToDateset is MEOS tstzset_to_dateset.
func (x *TsTzSet) ToDateset() (*Set, error) {
	_r0, _err := functions.TstzsetToDateset(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS tstzset_end_value.
func (x *TsTzSet) EndValue() (int64, error) {
	_r0, _err := functions.TstzsetEndValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// StartValue is MEOS tstzset_start_value.
func (x *TsTzSet) StartValue() (int64, error) {
	_r0, _err := functions.TstzsetStartValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ValueN is MEOS tstzset_value_n.
func (x *TsTzSet) ValueN(n int) (int64, bool, error) {
	_found, _value, _err := functions.TstzsetValueN(functions.SetFromPointer(x.Pointer()), n)
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Values is MEOS tstzset_values.
func (x *TsTzSet) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TstzsetValues(functions.SetFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// ShiftScale is MEOS tstzset_shift_scale.
func (x *TsTzSet) ShiftScale(shift *functions.Interval, duration *functions.Interval) (*Set, error) {
	_r0, _err := functions.TstzsetShiftScale(functions.SetFromPointer(x.Pointer()), shift, duration)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Tprecision is MEOS tstzset_tprecision.
func (x *TsTzSet) Tprecision(duration *functions.Interval, torigin int64) (*Set, error) {
	_r0, _err := functions.TstzsetTprecision(functions.SetFromPointer(x.Pointer()), duration, torigin)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// ToStbox is MEOS tstzset_to_stbox.
func (x *TsTzSet) ToStbox() (*STBox, error) {
	_r0, _err := functions.TstzsetToSTBOX(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}
